title: splunk installation guide
#logo:
description: how to install and setup splunk
#show_downloads: true
#theme: jeckyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
